---
- name: Build new host for VM
  hosts: localhost
  become: false
  tasks:
    - name: Create vm
      ansible.builtin.include_tasks: tasks/create-vm.yml

    - name: Create host record
      ansible.builtin.add_host:
        name: "{{ vm_name }}.{{ vm_domain_name }}"
        groups: new_vm

- name: Configure new VM
  hosts: new_vm
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Customize vm
      ansible.builtin.include_tasks: tasks/customize-vm.yml

    - name: Generalize vm
      ansible.builtin.include_tasks: tasks/generalize-vm.yml

    - name: Restart vm
      ansible.builtin.reboot:
