---
- hosts: localhost
  become: false
  vars_prompt:
    - name: vcenter_password
      prompt: enter vcenter password

    - name: vm_name
      prompt: enter name of vm
      private: no

    - name: vm_memory
      prompt: enter vm memory allocation
      private: no

    - name: vm_cpu
      prompt: enter vm cpu allocation
      private: no

    - name: vm_ip_address
      prompt: enter vm ip address
      private: no

  vars_files:
    - vars.yml
  
  tasks:
    - name: create vm
      ansible.builtin.include_tasks: create-vm.yml

    - name: create host record
      ansible.builtin.add_host:
        name: "{{ vm_name }}.{{ vm_domain_name }}"
        groups: new_vm


- hosts: new_vm
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: customize vm
      ansible.builtin.include_tasks: customize-vm.yml
    
    - name: generalize vm
      ansible.builtin.include_tasks: generalize-vm.yml

    - name: restart vm
      ansible.builtin.reboot:
        reboot_timeout: 1
      ignore_errors: True
