---
- name: Create VM from template
  community.vmware.vmware_guest:
    validate_certs: "{{ validate_certs }}"
    datacenter: "{{ vcenter_datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    datastore: "{{ vcenter_datastore }}"
    template: "{{ template_name }}"
    folder: "{{ vcenter_datacenter }}/vm"
    name: "{{ vm_name }}"
    state: poweredon
    customization:
      dns_servers: "{{ vm_dns_server }}"
      dns_suffix: "{{ vm_domain_name }}"
      domain: "{{ vm_domain_name }}"
      hostname: "{{ vm_name }}"
    hardware:
      memory_mb: "{{ vm_memory }}"
      num_cpus: "{{ vm_cpu }}"
    networks:
      - name: "{{ vm_network_name }}"
        type: static
        ip: "{{ vm_ip_address }}"
        netmask: "{{ vm_netmask }}"
        gateway: "{{ vm_gateway }}"
    wait_for_ip_address: true
