---
- name: Attach RHEL subscription
  community.general.redhat_subscription:
    activationkey: "{{ activation_key }}"
    org_id: "{{ org_id }}"

- name: Upgrade packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true

- name: Set chrony config
  ansible.builtin.copy:
    src: chrony.conf
    dest: /etc/chrony.conf
    mode: '0644'
